### ISSUE TITLE
Gmail reply header parser problem with languages different to english

### ISSUE THREAD

**Issue by patriciagao** [thoughtbot/griddler#163]
The Gmail header parser problem that was fixed here #120 doesn't work if the language is different to english due the regex (it includes the word `wrote`).

<pre>/^\s*\>?\s*On.*\r?\n?\s*.*\s*<b>wrote</b>:\r?\n?$/</pre>

For other languages, such as Spanish where the new line looks like this:
`El 27 de junio de 2014, 13:55, <name@email.com> escribió:` The solution doesn't work.

Could make sense to change the regex to something like this??
`/^\s*\>?\s*On.*\r?\n?\s*.*\s*:\r?\n?$/`

**Comment by bytestream** [comment]
Sorry to dig up an old thread but I was wondering if anything developed from this issue or is it still unsupported?

**Comment by Hamdan85** [comment]
It is still failing on pt-br.
