### ISSUE TITLE
Should allow for BCC field to be parsed. 

### ISSUE THREAD

**Issue by jonathan-mui** [thoughtbot/griddler#168]
I'm building out a CRM system right now and I have a use case for using the BCC field. If a user responds to a sales lead, they may want to respond to the lead and BCC our leads@domain.com receiving address to log the email conversation.

I know there are other alternatives such as email syncing (POP/IMAP) and forwarding sent emails to leads@domain.com, but I think having the BCC could allow more flexibility.

The introduction of BCC was first discussed here: https://github.com/thoughtbot/griddler/pull/95

**Comment by dominicsayers** [comment]
I've added a PR to handle BCCed emails in the Cloudmailin adapter. I don't think anything needs to change in Griddler itself https://github.com/thoughtbot/griddler-cloudmailin/pull/3
