### ISSUE TITLE
A copy of EmailProcessor has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by nambrot** [thoughtbot/griddler#170]
This is on a brand new Rails install (admittedly 4.2.beta1, but it's not Spring related).

All default settings, an EmailProcessor that just prints out a debug message. When the server is running and I modify the EmailProcessor, it throws that error.

**Comment by rdetert** [comment]
I'm still seeing this with: 

Rails 4.1.9
Ruby 2.0.0-p481
griddler (1.1.0)
