### ISSUE TITLE
It raise EmailProcessor NameError when there is no config file.

### ISSUE THREAD

**Issue by ugoa** [thoughtbot/griddler#187]
I put the `email_proccessor.rb` in the `lib` folder and set the autoloading, but without a `griddler.rb` config file, for which I meant to use all the default settings. but it turned out to give me `NameError`, I have checked the code and found this:
```
if Kernel.const_defined?(:EmailProcessor)
  EmailProcessor
else
  raise NameError.new(<<-ERROR.strip_heredoc, 'EmailProcessor')
              To use Griddler, you must either define `EmailProcessor` or configure a
              different processor. See https://github.com/thoughtbot/griddler#defaults for
              more information.
  ERROR
end
```
So `Kernel.const_defined?(:EmailProcessor)` always returns `false` while `EmailProcessor` actually can be loaded. but it will return `true` when there is a config file, in which has such code:
```
config.processor_class = EmailProcessor
```
Here the `EmailProcessor` has been called, so it's loaded correctly since then and this is why it return `true`.
So the problem is, in the document it says the `griddler.rb` file is optional, which apparently is not. Please do a update to the document or change the `if...else...` logic or something else.
Thanks.

**Comment by egoodberry** [comment]
If the config is required, it should be called out in the README, whether or not this is intended to be changed in the future.

The line

`An initializer can be created to control some of the options in Griddler.`

should be changed to

`An initializer *must* be created and can be used to control some of the options in Griddler. `

**Comment by gabebw** [comment]
I don't think a config file is necessary, unless I missed something. We certainly don't want it to be.

I'm closing this, but I'm listening for new comments about whether a config file is required.

**Comment by costa** [comment]
Doing the griddler setup by the book (the current README) brings an unsuspecting developer to this issue.
@gabebw How a config file is unnecessary? Can griddler guess which adapter to use without the config? How the issue above can be avoided without a config file?
Thank you!

**Comment by aqabawe** [comment]
@gabebw yep, I'm getting a NameError on 1.2.1 as well.
