### ISSUE TITLE
Message uniqueness

### ISSUE THREAD

**Issue by grepruby** [thoughtbot/griddler#189]
Is there any way to validate uniqueness of email ? I am using sendgrid, and it keeps on sending email until our app respond with 200. So I just wanted to make sure on app if db has been updated already for any message or not .

I check the headers and It has "Message-ID" attribute . Is it fine to use it for validating uniqueness ?

Thanks!!

**Comment by nhocki** [comment]
@grepruby you should probably process the email inside a background job and send a `200` instantly to Sendgrid... but anyway, according to [Wikipedia](http://en.wikipedia.org/wiki/Message-ID):

> Message-IDs are required to have a specific format which is a subset of an email address and to be globally unique.

**Comment by calebthompson** [comment]
Confirmed.
