### ISSUE TITLE
Run travis against 4.2

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/griddler#192]
While you're at it, Griddler has historically mimicked the supported versions for Ruby and Rails, so I think 4.0 might be able to be dropped, or it could be security only.

**Comment by gabebw** [comment]
Is 4.0 no longer officially supported?

**Comment by calebthompson** [comment]
Nope: http://guides.rubyonrails.org/maintenance_policy.html

**Comment by gabebw** [comment]
It looks like 4.1.x and 4.2.x are the only versions that have any support at all (and 3.2.x for security issues, but let's ignore that).

**Comment by calebthompson** [comment]
Agreed.
