### ISSUE TITLE
Exception when receiving email with a blank body

### ISSUE THREAD

**Issue by qmclaugh** [thoughtbot/griddler#200]
If I receive an email with an attachment and no body Griddler crashes.  Using Apple Mail and Mailgun; bug appears to be in Griddler.

NoMethodError (undefined method `valid_encoding?' for nil:NilClass):
 ** [out :: ] /var/www/apps/liquidsign/shared/bundle/ruby/2.0.0/bundler/gems/griddler-d35287f90f5e/lib/griddler/email.rb:76:in `clean_invalid_utf8_bytes'
 ** [out ::] /var/www/apps/liquidsign/shared/bundle/ruby/2.0.0/bundler/gems/griddler-d35287f90f5e/lib/griddler/email.rb:69:in `clean_html'
 ** [out ::] /var/www/apps/liquidsign/shared/bundle/ruby/2.0.0/bundler/gems/griddler-d35287f90f5e/lib/griddler/email.rb:61:in `text_or_sanitized_html'
 ** [out ::] /var/www/apps/liquidsign/shared/bundle/ruby/2.0.0/bundler/gems/griddler-d35287f90f5e/lib/griddler/email.rb:48:in `extract_body'

**Comment by gabebw** [comment]
Thanks for reporting this! I'm closing this in favor of discussion in your PR in #201.
