### ISSUE TITLE
Forwarded email missing body

### ISSUE THREAD

**Issue by theinventor** [thoughtbot/griddler#203]
Hey guys - cool toys :)

So, I have mac mail, and I'm forwarding an email into sendgrid/griddler, and the body is just:

```
> Begin forwarded message:
> 
>
```

From this email:

(quite a bit of good valid html)

![image](https://cloud.githubusercontent.com/assets/610029/7080763/334ac27c-deec-11e4-953f-3fdc0e19302f.png)

What are people doing when they want to get at the whole thing, like in this case?

**Comment by calebthompson** [comment]
Should be in raw_body
