### ISSUE TITLE
Linked blog has outdated installation instructions

### ISSUE THREAD

**Issue by egoodberry** [thoughtbot/griddler#204]
The blog post linked from the README (https://robots.thoughtbot.com/handle-incoming-email-with-griddler) explicitly states that a route is automatically generated when Griddler is installed; this is no longer the case and is very confusing to someone using the article as a guide, which is what the README seems to be encouraging.

Recommended would be to update the blog post, at minimum remove the reference from the README.

**Comment by gabebw** [comment]
Thanks for bringing this to our attention! I've been thinking about this issue for a while (but didn't write anything, oops!) and finally published a blog post: https://robots.thoughtbot.com/griddler-is-better-than-ever
