### ISSUE TITLE
Message Forwarding

### ISSUE THREAD

**Issue by brandonparsons** [thoughtbot/griddler#22]
How would I use `ActionMailer` to just forward this straight along - **attachments and all** ?  Thanks!

**Comment by pdoggi** [comment]
@hovancik Thanks for posting! Super helpful!

Would anyone know how to test with Rspec + FactoryGirl forwarding emails with attachments?

**Comment by rdetert** [comment]
@hovancik This still doesn't work for me. Can you post your whole class? I'm sending out through Mandrill, not sure if that makes a difference.

**Comment by hovancik** [comment]
@rdetert 
my mailer looks like this: 

```
class MyMailer < ActionMailer::Base
	def send_email(from,to,reply,subject,body,attach)
		#attach attachments
		attach.each do |attachment| 
			attachments[attachment.original_filename] = File.read(attachment.tempfile)
		end
		mail(	from: from, to: to, reply_to: reply, subject: subject, body: body	)
	end
end
```

and then I call it like `      	MyMailer.send_email(email.from,to,reply,email.subject,email.raw_body,email.attachments).deliver`

This was Gridller 0.6 or something. But I believe email.attachments is still array in newer Griddler

**Comment by rdetert** [comment]
Your solution still works. The problem was with Mandrill and (at least) inline attachments. Switching to Sendgrid works fine. More on the issue can be found here: https://github.com/wingrunr21/griddler-mandrill/issues/15
