### ISSUE TITLE
Extracting the email address this delivery is for

### ISSUE THREAD

**Issue by pandamouse** [thoughtbot/griddler#224]
Let's say different actions dependent on different incoming email address (e.g. attach+123@domain.com will do attachment process on certain records and attach+345@domain.com will do attachment for another set of records) and an email is sent with multiple address that are meaningful to the system and the system receives that multiple times (as many times as the meaningful address appears). The only way for the system to get the recipient that this email is intended is to look into certain parameter ( params[:recipient] in mailgun's case).

Is there an attribute in the email class that give us the delivered_for email address?

**Comment by rdetert** [comment]
No, you'll have to parse `raw_headers` manually.

**Comment by pandamouse** [comment]
Ok thanks
