### ISSUE TITLE
Adapter specific configuration

### ISSUE THREAD

**Issue by wingrunr21** [thoughtbot/griddler#225]
Wanted to open an issue on this before putting together a PR.

I've got a use case where a user would like a configuration option for the Mandrill adapter (see wingrunr21/griddler-mandrill#23). Right now I am considering three approaches:
- Add some kind of `adapter_config` attribute to `Gridder::Configuration` which is passed into `new` in `Griddler::EmailsController`. The `adapter_config` would be an arbitrary hash that the adapter would then consume as needed (in my case configuring SPF checks).
- Allow the `email_service` config option to accept an optional hash of additional configuration. The rest would function like the `adapter_config`
- Add a new configuration object in the adapter itself. I am less partial to this as it feels a little weird having the adapter configure itself in addition to the parent project.

Any thoughts on this?

**Comment by gabebw** [comment]
If I understand your first bullet point correctly, then [this line](https://github.com/thoughtbot/griddler/blob/f180df236598cb98da9f947571728b0e62f534db/app/controllers/griddler/emails_controller.rb#L18-L20) changes from 

```ruby
processor_class.new(email).public_send(processor_method)
```

to 

```ruby
if extra_configuration?
  processor_class.new(email, extra_configuration).public_send(processor_method)
else
  processor_class.new(email).public_send(processor_method)
end
```

(I added the `if` so that adapters that only take 1 arg don't break.) I like that version the best.

**Comment by wingrunr21** [comment]
Ya, that's what I meant.

We can also check the arity of `new` to protect adapters or increment the griddler version (since this is an API change) and just have adapters depend on the older version until they update.

**Comment by gabebw** [comment]
> increment the griddler version (since this is an API change)

Yes, good point. I like that idea better, since as you point out, this is a breaking change.

**Comment by micahbf** [comment]
Would love to see this merged! I ran into the exact issue @wingrunr21 describes - we need to be able to configure SPF checking in griddler-mandrill. In the mean time we will probably need to maintain our own fork of the adapter gem.

**Comment by wingrunr21** [comment]
@micahbf agreed, I need to get back on getting this change pushed out. I'm a bit swamped right now but I will try and find time.

**Comment by micahbf** [comment]
@wingrunr21 Let me know if I can help.
