### ISSUE TITLE
getting the email's html body

### ISSUE THREAD

**Issue by bmccoelho** [thoughtbot/griddler#226]
hi,

I'm trying to filter some content of the email's html body. 
my goal is to remove gmail's signature that are inside a div with class 'gmail_extra':
```HTML
<div class="gmail_extra"> ... </div>
```
but I'm having an hard time getting the email's html body, I always get the text version in the `email.body` (I'm using the standard reply delimiter).

I know I can always use the `email.raw_html` but that way I would loose the pre-processing done by griddler, which is great and I want it.

from what I could see the reason for that is in these 2 lines [here](https://github.com/thoughtbot/griddler/blob/master/lib/griddler/email.rb#L64):
```ruby
def text_or_sanitized_html
  text = clean_text(params.fetch(:text, ''))
  text.presence || clean_html(params.fetch(:html, '')).presence
end
```
is this an intended behaviour? can this be change in the config?

if not, would you be willing to accept a Pull Request that would make this configurable? 

thanks in advance,
bruno

**Comment by gabebw** [comment]
Hmmm, you could get the html body by doing this in your email processor: `EmailParser.extract_reply_body(email.raw_html)`, though that's not all of the processing we do (it won't strip UTF8 bytes or tags, though you might want that).

Does that code get you what you want?

**Comment by bmccoelho** [comment]
yes, I can work from there and loosing the `clean_html` in `email.rb`.

I manage to get what I want by changing the `text_or_sanitized_html` like this:
```ruby
def text_or_sanitized_html
  html = clean_html(params.fetch(:html, ''))
  html.presence || clean_text(params.fetch(:text, '')).presence
end
```

and tap in the `clean_thml`:
```ruby
def clean_html(html)
  cleaned_html = clean_invalid_utf8_bytes(html)
  cleaned_html = remove_gmail_extra_tag(html) # <-- here
  cleaned_html = strip_tags(cleaned_html)
  cleaned_html = HTMLEntities.new.decode(cleaned_html)
  cleaned_html
end

def remove_gmail_extra_tag(html)
  doc = Nokogiri::HTML.fragment(html)
  node = doc.css("div.gmail_extra")
  node.remove if node # if exists removes gmail signatures above standard separator "-- "
  doc.to_s
end
```

what do you think about it?
do you think it's useful as a configurable option?

**Comment by wingrunr21** [comment]
@bmccoelho I believe your updated `clean_html` method would be better served within your use case instead of as a configuration option. However, I agree that a better method of getting the sanitized HTML body is required. I have opened #243 for that.

Thanks!

**Comment by LoveUlitka** [comment]
Hi there!
And what is mean '3D"gmail_extra"?'
