### ISSUE TITLE
Is that possible to receive emails from different email addresses?

### ISSUE THREAD

**Issue by KranthiKishore** [thoughtbot/griddler#231]
I have given each user a unique email address to which user can send email. I want to receive email when user sends  email to that particular unique email address in rails app. Is that possible with griddler?

**Comment by wingrunr21** [comment]
Yes, this should be possible. Griddler merely provides an API endpoint for the various adapters to POST incoming email data + normalization of various data formats the different providers use. The [tutorials](https://github.com/thoughtbot/griddler#tutorials) should help get you up and running. You'll just need to set up whatever provider you choose to hit the Griddler endpoint for your disparate email addresses.

I'm going to go ahead and close issue.
