### ISSUE TITLE
Bounce back email handling

### ISSUE THREAD

**Issue by coreymartella** [thoughtbot/griddler#234]
We're hitting a major infinite loop issue in using griddler in combination with outbound mailers:

1. User posts a comment
1. Comment mailer sends notification to all other users, one of which is a bad email
1. Inbound emails from the sender of the mail above are treated as new comments
1. Bounce back email gets handled as a new comment and starts the process over

Any recommendation how we might handle this? Is there a way to make sendgrid send bounces to a different address? Is there a header or consistent locale-indifferent string to look for in the body?

**Comment by bradpauly** [comment]
This might be a question best answered by Sendgrid. Is your comment mailer sending via sendgrid? If you're using webhooks for the responses I don't think you should be seeing bounces. Do you set a Reply-To that is different from the sending address?

**Comment by wingrunr21** [comment]
I am going to close this as it is a SendGrid specific question. If it is still an issue, can you open up something over at thoughtbot/sendgrid? Thanks!
