### ISSUE TITLE
Issue with griddler-sendgrid

### ISSUE THREAD

**Issue by rememberlenny** [thoughtbot/griddler#237]
I setup on the sendgrid-parse and I wasn't getting the body/body_raw content to populate correctly. I transitioned to using mandrill and everything is working. Its not an issue with Griddler, but I'd like to flag for other users.

**Comment by gabebw** [comment]
This sounds like an issue for https://github.com/thoughtbot/griddler-sendgrid ?

**Comment by wingrunr21** [comment]
Closing as thoughtbot/griddler-sendgrid#9 tracks this
