### ISSUE TITLE
Default reply_delimiter internationalization?

### ISSUE THREAD

**Issue by bdmac** [thoughtbot/griddler#240]
I just noticed that the default reply_delimiter, which works great in English, does not work when receiving email replies in other languages. The delimiter that should be searched for is basically the same just not in English.  For example, in this specific case the email contains:

```
El 11 ene 2016, a las 23:43, 661 70 68 72 <reply@domain.com> escribió:\n> \n> Recipient
```
which roughly translates to something that should match this part of the default regex:
```
/On.*wrote:/
```

Is there any plan currently to add internationalization of these defaults? These defaults currently only work for English emails and it's not like the recipient using griddler can control the sender's language of choice.

**Comment by calebthompson** [comment]
No, but it can be configured. https://github.com/thoughtbot/griddler/blob/master/lib/griddler/email_parser.rb#L58
https://github.com/thoughtbot/griddler#configuration-options

**Comment by bdmac** [comment]
I see that but many gems provide internationalization for things like this and request/accept translations from the community. It seems like this may be a good idea for Griddler instead of assuming the world only speaks English. At the very least perhaps a note about this fact in the documentation could be useful.

I also see an unconfigurable English assumption in EmailParser here: https://github.com/thoughtbot/griddler/blob/master/lib/griddler/email_parser.rb#L35

**Comment by calebthompson** [comment]
Feel free to open a PR to make that configurable, but I don't think we're interested in maintaining a set of translations at this point.

We're currently seeking a new maintainer for Griddler, so if you or someone else would like to take over the gem and maintain translations we'd be open to discussing that.
