### ISSUE TITLE
Looking for a new maintainer for Griddler

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/griddler#241]
Griddler has a fair number of open PRs and issues and deserves better maintainance.

Thus, **thoughtbot is looking for a new maintainer for Griddler**.

Besides the open PRs and issues, maintaining Griddler means keeping compatibility with all of the Griddler adapters (like griddler-sendgrid). For example, #212 was related to an issue in griddler-mandrill.

Are you interested? Comment in this issue. Strong preference will be given to Griddler contributors and current maintainers of Griddler adapters.

--------------------------------------------------------------------------

We are also **looking for a maintainer for [griddler-cloudmailin](https://github.com/thoughtbot/griddler-cloudmailin) and [griddler-sendgrid](https://github.com/thoughtbot/griddler-sendgrid)**.

If you're interested in those adapters, comment [here for griddler-cloudmailin](https://github.com/thoughtbot/griddler-cloudmailin/issues/8) and [here for griddler-sendgrid](https://github.com/thoughtbot/griddler-sendgrid/issues/10).

/cc @r38y @jayroh @sendgrid @bradpauly @wingrunr21 @theycallmeswift

**Comment by kelvinst** [comment]
Hey, I'm interested!!! :grin:

**Comment by wingrunr21** [comment]
I'd be willing to maintain/help out with maintenance.

**Comment by gabebw** [comment]
@wingrunr21 Thanks! I've made you an admin of this repository.

If you have any questions, feel free to email me at gabebw@gabebw.com.

**Comment by scsmith** [comment]
@wingrunr21 I didn't think I'd be able to spare the time to give this justice but I'm more than happy to help if/where we can (Founder of CloudMailin, now helping maintain griddler-cloudmailin).
