### ISSUE TITLE
Configuring Reply Delimiter Broken

### ISSUE THREAD

**Issue by zephyr-dev** [thoughtbot/griddler#246]
When configuring the Reply Delimiter using the `config.reply_delimiter = "-- Reply Above --"` example in the documentation, we get: `undefined method `reply_delimiter=' for #<Griddler::Configuration:0x0000000de7d288> (NoMethodError)`

It looks like this functionality was broken here: https://github.com/thoughtbot/griddler/commit/57bc70e8d510ebbde6e0244855ade1e07ee2251f#commitcomment-16423907

**Comment by wingrunr21** [comment]
I commented directly in the PR. Thanks. It is likely this was removed accidentally.

**Comment by zephyr-dev** [comment]
@wingrunr21 no worries, we're happy to wait for the new pull request from @joeadcock

**Comment by wingrunr21** [comment]
Just merged it

**Comment by zephyr-dev** [comment]
Thank you!
