### ISSUE TITLE
Heroku rake db:migrate leads to NoMethodError: undefined method 'split' for nil:NilClass

### ISSUE THREAD

**Issue by christudor** [thoughtbot/griddler#249]
Everything working fine on the development environment. However, when it comes to deploying to Heroku, when I try to run 'heroku rake db:migrate', I get the following error message:

`rake aborted!
NoMethodError: undefined method 'split' for nil:NilClass
/app/vendor/bundle/ruby/2.0.0/gems/rollbar-1.2.13/lib/rollbar/rake.rb:23:in 'patch?'
/app/vendor/bundle/ruby/2.0.0/gems/rollbar-1.2.13/lib/rollbar/rake.rb:6:in 'patch!'
/app/vendor/bundle/ruby/2.0.0/gems/rollbar-1.2.13/lib/rollbar/rake.rb:38:in '<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'block in require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in 'load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'require'
/app/vendor/bundle/ruby/2.0.0/gems/rollbar-1.2.13/lib/rollbar.rb:684:in 'require_hooks'
/app/vendor/bundle/ruby/2.0.0/gems/rollbar-1.2.13/lib/rollbar.rb:653:in 'configure'
/app/config/initializers/rollbar.rb:2:in '<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in 'load'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in 'block in load'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in 'load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in 'load'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/engine.rb:588:in 'block (2 levels) in <class:Engine>'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/engine.rb:587:in 'each'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/engine.rb:587:in 'block in <class:Engine>'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/initializable.rb:30:in 'instance_exec'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/initializable.rb:30:in 'run'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/initializable.rb:55:in 'block in run_initializers'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/initializable.rb:54:in 'each'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/initializable.rb:54:in 'run_initializers'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/application.rb:136:in 'initialize!'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in 'method_missing'
/app/config/environment.rb:5:in '<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'block in require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in 'load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in 'require'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/application.rb:103:in 'require_environment!'
/app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/application.rb:297:in 'block (2 levels) in initialize_tasks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)`

Can someone help me debug?

**Comment by wingrunr21** [comment]
This is related to rollbar and not this gem. Please see rollbar/rollbar-gem#396
