### ISSUE TITLE
Add Inbound Parse settings to README

### ISSUE THREAD

**Issue by acmeyer** [thoughtbot/griddler#251]
Wasn't sure where to put this one but hope to save others some trouble in the future:

I was having issues setting up griddler with SendGrid, the body text wasn't appearing. After a lot of headache, I figured out what was wrong. When setting up Inbound Parse settings in your dashboard in SendGrid, make sure to uncheck "Spam Check" and "Send Raw" settings for your parser. Spam check stripped out the body content because it thought some emails were spam (I'm sure there is more you could do to set spam filters correctly). Send Raw was, I am guessing, sending the email in a way that griddler (I have the sendgrid griddler adapter gem too) couldn't find the body content and therefore generated nothing. 

Once I removed both of these settings, everything worked as expected. Hope to save others similar headaches setting up there inbound email parsers.

**Comment by wingrunr21** [comment]
Hi,

Thanks for this info. However, this gem is not SendGrid specific. Would you mind opening an issue over at thoughtbot/griddler-sendgrid?

Thanks

**Comment by acmeyer** [comment]
yup, done
