### ISSUE TITLE
Tweaks needed for clean implementation of an Amazon SES adapter

### ISSUE THREAD

**Issue by kmewhort** [thoughtbot/griddler#255]
I have an adapter for Amazon SES/SNS ready to go:  https://github.com/85x14/griddler-ses.  It's fully working, but there are a couple of hacks that I'd like to clean-up:

**1. Need access to the raw request**

AWS unfortunately sets the content type of it's JSON messages to `text/plain` (see https://forums.aws.amazon.com/thread.jspa?messageID=418160).  This means that Raills doesn't parse it into `params`. 

As a workaround, I'm using introspection to get the `request` object from the calling controller -- `binding.of_caller(2).eval('request')` :sob:.  Any ideas on a nicer way we could do this? Maybe griddler could pass in the `request` as a second optional parameter to `normalized_params`?

**2. Need to cancel non-reply requests**

Some the requests coming through the endpoint are just for confirming subscription to the AWS SNS API.  These need to be handled, but are not actually replies.  I'm just returning an empty hash for the parameters in this case, but it means that clients likewise have to handle the case where the parameters are empty (in my client code, I check for `email.headers.empty?` at the moment).

Could we have a way to cancel processing?

**Comment by wingrunr21** [comment]
1) I am really not thrilled with allowing the `request` to leak outside the controller. This seems like a good case for some Rack middleware.
2) I'm not sure what you mean by "cancel the processing". The processing is simply a method call. You'd want logic to not call the method for a given heuristic right?

I am wondering if this is a good use case for #254. Griddler could ship a basic controller that handles most use cases. Amazon SES could either ship its own controller or provide instructions on controller implementation.

**Comment by kmewhort** [comment]
Yes, logic to not call the hook for a given heuristic is what I was thinking of for #2.  Thinking more about this though, it might make sense and work to try to handle these non-reply HTTP requests right in middleware as well.  I'll take a stab at going this route.

**Comment by kmewhort** [comment]
I added middleware to `griddler-ses` to handle and correct AWS's buggy content-type header.  This approach works well, so closing this issue.
