### ISSUE TITLE
Identify duplicate emails

### ISSUE THREAD

**Issue by vedant1811** [thoughtbot/griddler#258]
Due to some error (outside my rails app) I am receiving multiple emails. They end up being processed each time and I get multiple entries.

What would be a nice way to uniquely identify an email? For my purpose, the combination of the body and attachments make the email unique. Is there some other data shared by most email providers to identify emails, or, can I expect the `@email.attachments` to be same for the emails- then I can hash the body and the attachments together and store it.

This issue probably is more of a "question" than a "feature request", and is definitely not a "bug" :)

**Comment by wingrunr21** [comment]
Well the `Message-ID` header should be unique for every email. You could take a look at that to determine whether you've already seen the message.

**Comment by vedant1811** [comment]
@wingrunr21 thanks! :) Just for future reference the `Message-Id` header can be accessed by `@email.headers['Message-Id']` (and not `Message-ID`)
