### ISSUE TITLE
Mail::AddressList can not parse UTF-8 name in to field

### ISSUE THREAD

**Issue by hajder** [thoughtbot/griddler#277]
I do understand it is not a Griddler issue but since it's a known bug in Mail for many years and it doesn't seem to be ever fixed I thought maybe a workaround in Griddler would make sense.

When an address field contains non-ascii characters (in my case German ü) Mail parser fails in a following message:

```
Mail::Field::ParseError: Mail::AddressList can not parse |Robert Smith <robert@example.com>, Mike Mürkins <mike.muerkins@example.com>|
Reason was: Only able to parse up to Robert Smith <robert@example.com>, Mike Mü
```

This seems to be related to #214 & #215. I'm using version 1.3.1 with Sendgrid and this is the backtrace

```
  from mail/parsers/address_lists_parser.rb:15:in `parse'
  from mail/elements/address_list.rb:23:in `initialize'
  from griddler/sendgrid/adapter.rb:27:in `new'
  from griddler/sendgrid/adapter.rb:27:in `recipients'
  from griddler/sendgrid/adapter.rb:15:in `normalize_params'
  from griddler/sendgrid/adapter.rb:10:in `normalize_params'
  from griddler/emails_controller.rb:17:in `normalized_params'
  from griddler/emails_controller.rb:3:in `create'
```

**Comment by hajder** [comment]
Issue in Mail
https://github.com/mikel/mail/issues/39
https://github.com/mikel/mail/issues/299

**Comment by wingrunr21** [comment]
Hmm, interesting. Do you have a workaround that you are using successfully?

**Comment by hajder** [comment]
@wingrunr21 I do not. I just noticed this in my error reporting and since it's 1:30am and I would like to go home I figured reporting this in a right place would be a solution :D

**Comment by cmunozgar** [comment]
@hajder Did you find a solution for this error?

**Comment by hajder** [comment]
@cmunozgar No. Didn't have time to work on it since this problem doesn't have a high priority at the moment.

**Comment by wingrunr21** [comment]
So I'm open for suggestions on solving this. Since the baseline parsing is in the Mail gem (and the bug is also there), I'm not clear how to solve it short of switching the parse to something else. We could subclass the Mail gem and fix the requisite parts, but my concern with that is around different behavior between how Griddler is handling mail parsing vs the rest of the rails app. Thoughts?

**Comment by jeremy** [comment]
Check out https://github.com/mikel/mail/pull/1103. UTF-8 header parsing lands in Mail 2.7.0 😊

**Comment by hajder** [comment]
@jeremy that's great news, can the dependency be updated?

**Comment by jeremy** [comment]
@hajder 2.7.0 is in release candidate now. Maybe after release!

**Comment by wingrunr21** [comment]
@hajder Griddler does not have a fixed dependency on the Mail gem. We use it via our Rails requirement.

I am going to close this issue as if Mail has pushed a fix there's nothing to be done here.
