### ISSUE TITLE
Remove Email Logging

### ISSUE THREAD

**Issue by fong2317** [thoughtbot/griddler#290]
Every time my email processor receives an email, it prints the entire email into my rails log. Is there any way I can remove this functionality so it doesn't print everything?

**Comment by wingrunr21** [comment]
This has nothing to do with Griddler. This is standard Rails procedure for incoming parameters. You'll need to identify which parameters your provider of choice is sending to your app and then use something like [Rails parameter filtering](http://guides.rubyonrails.org/action_controller_overview.html#parameters-filtering) to keep them from being printed to the logs.

**Comment by fong2317** [comment]
Thank you for the help!
