### ISSUE TITLE
Allow using multiple email services

### ISSUE THREAD

**Issue by ygnessin** [thoughtbot/griddler#291]
Does griddler support multiple email services and adapters at once? If yes, how, and if not, this is a feature request.

Usecase:
I am migrating a service from Sendgrid to Sparkpost. There will be an intermediate period where we will be sending emails from both, and receive webhooks from both. But I can't see a way to do that out of the box. Please correct me if I'm missing something.

Thank you!

**Comment by wingrunr21** [comment]
It does not currently support multiples.

Right now, the only limiting factor for you would be making sure an incoming request hits the correct adapter. If you are running the services on different endpoints, you could subclass the Griddler controller for a given endpoint that would encapsulate the various configuration. You then may be able to use a refinement to update the configuration within that controller.

**Comment by ygnessin** [comment]
Thanks for the suggestion! I'll update you if that works. Appreciate the help.
