### ISSUE TITLE
Unclear purpose in readme. 

### ISSUE THREAD

**Issue by adiakritos** [thoughtbot/griddler#301]
You should make the very first line of the readme say this: 

"Griddler allows your Ruby on Rails application to receive email."

The line goes straight into a HOW it does what it does and assumes the reader knows why they would want an endpoint that converts whatever into a POST request.

**Comment by wingrunr21** [comment]
The first line of the README is accurately describing the gem. Griddler requires an external service to convert incoming email to an HTTP Post request. It isn't actually receiving email and adding a README entry that says it allows a Rails app to do so would be inaccurate.

**Comment by adiakritos** [comment]
@wingrunr21 I didn't say anything about accuracy. I said UNCLEAR PURPOSE.

**Comment by wingrunr21** [comment]
@adiakritos I'm happy to answer questions but not super thrilled with the tone you're taking here.

This project normalizes out HTTP POST requests for various email services that provide an inbound parse service. Basically, these services allow people to send email to them (via a configurable email address), they parse that email into its disparate parts, and then POST that email to the API endpoint that you've configured.

Most of these services POST via some kind of JSON envelope. Griddler exposes the controller action and then allows an adapter system to allow that JSON envelope to be normalized (see [adapter list here](https://github.com/thoughtbot/griddler#adapters)).

So, you use the project to "receive" email but not in the same sense has having an actual inbox. You have to have one of the external services to actually do the email receive + parse + POST.
