### ISSUE TITLE
Cannot fetch the MIME information written between the boundary line and raw body

### ISSUE THREAD

**Issue by RubyLucy** [thoughtbot/griddler#313]
**UPDATED on Nov.14:**
**The problem is as the title describes, the original post is just an example to explain how the problem impacts my case.**
The information ignored by griddler is the charset information in my example, it is written between the boundary line and email raw body.

> Content-Type: text/plain;  charset=ISO-2022-JP
> Content-Transfer-Encoding: 7bit

Griddler can fetch the text written before the boundary line (in my example it's "----==_mimepart_5d679b0e8920c_bca3fe4beb466ac88238") as raw_header, and the text in email body (in my example it starts from the garbled text as you can see) as raw_body, but sometimes some emails like to put some texts between the boundary line and the raw body (In my example it is the charset information), and it cannot be fetched by griddler now.

The expectation is: DO NOT MISS ANY TEXT IN THE EMAIL SOURCE.

**ORIGINAL POST:**
- The following code is the source code of the email that I received and want to post into my Rails app via griddler. 

- This email is in Japanese and encoded with charset "iso-2022-jp" thus it is probably garbled in your browser. And it is indeed garbled as it shows in my app.

- What I want to do is to fetch the charset information, if it is "iso-2022-jp", then do encode("utf-8", "iso-2022-jp") for the raw_body so that the Japanese can show normally in my app. If it is already "utf-8" then do nothing.

- **The problem is** griddler's #raw_headers attribute can only fetch the information before the boundary line, while #raw_body starts from the line after "Content-Transfer-Encoding: 7bit", thus it seems that I have no way to get the charset information that I want via griddler.

**Could somebody help fix this problem?**

```
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="--==_mimepart_5d679b0e8920c_bca3fe4beb466ac88238"

----==_mimepart_5d679b0e8920c_bca3fe4beb466ac88238
Content-Type: text/plain;  charset=ISO-2022-JP
Content-Transfer-Encoding: 7bit

$B2q0w8BDj(IR0YO6^<^](B

8$B7n(B31$BF|$O(I"$BLn:Z$NF|(I#$B$G$9!#(I:=D:$B$G$O9qFb30$+$i?7A/$J(ILY(B-(IB$B!"Ln:Z$r<h$jB7$($F$$$^$9!#(B
GAP$BG'>Z$5$l$?>&IJ$r<h$j07$$$r=g<!3HBg$7$F$$$^$9!#>\$7$/$O$3$A$i$r%/%j%C%/(B (PC$B@lMQ(B)$B!#(B

**Comment by RubyLucy** [comment]
@christoomey 
Sorry for '@'ing you, but I think it's a more efficient way to solve this problem.

**Comment by theasteve** [comment]
@RubyLucy I think this is due to the wrong conversion of MIME email messages for Japanese language. If no one is working on this issue I'm more than happy to work on a PR 👍!

**Comment by theasteve** [comment]
@RubyLucy can you help me reproduce this issue. What is the Japanese text used on this email?

**Comment by RubyLucy** [comment]
> @RubyLucy can you help me reproduce this issue. What is the Japanese text used on this email?

Hi Steven,

It has nothing to do with Japanese text or not. The problem is, as I wrote in the title, "Cannot fetch the MIME information written between the boundary line and raw body". Any information written between email boundary line and email raw body is IGNORED by griddler, in my example, it was the charset information. 
```
Content-Type: text/plain;  charset=ISO-2022-JP
Content-Transfer-Encoding: 7bit
```

I'm sorry that my example might have confused you, but it was just an example to describe the problem.
