### ISSUE TITLE
Release 1.6.0 - what is included?

### ISSUE THREAD

**Issue by davidwessman** [thoughtbot/griddler#326]
Hello!

Cannot see any new commits, tags, issues or PRs but a version 1.6.0 dropped.
What has changed?

**Comment by Aesthetikx** [comment]
I noticed this as well... seems [harmless](https://my.diffend.io/gems/griddler/1.5.2/1.6.0) but we should hear from @calebhearth ?

**Comment by calebhearth** [comment]
Hey I’m maintaining this at https://github.com/calebhearth/griddler. The commits, tag, etc. should be there. Thanks for checking, all good!

**Comment by davidwessman** [comment]
> Hey I’m maintaining this at https://github.com/calebhearth/griddler. The commits, tag, etc. should be there. Thanks for checking, all good!

Nice!

Could you update the rubygems config as well so the changelog makes sense in Dependabot PRs?

**Comment by jeffbax** [comment]
> Hey I’m maintaining this at https://github.com/calebhearth/griddler. The commits, tag, etc. should be there. Thanks for checking, all good!

Went in a circles a bit given that the latest tag there seems to be 1.2.1 from 2015, and not the usual `CHANGELOG.md` rather a `NEWS.md` that might be helpful to reference for `bundle info` -- figured worth pointing out a bit that it was a little roundabout as you can't utilize the Github "tags" or "releases" features much.

**Comment by davidwessman** [comment]
@stefannibrasil You were the last Thoughtbot-person who made a commit here, is it expected that Caleb handles this on his personal Github? If that is the case, then it would be great if this repo could be archived and a note added to the Readme explaining that is the case.

**Comment by stefannibrasil** [comment]
Hi, all! Thanks for opening this issue.

Yes, I talked with folks at thoughtbot and this one should be deprecated in favor of ActionMailer since this is built into Rails now. I will do that now. Thanks!
